version: "3.8"

####
#   - DB backends port 5432 for access manager
#
# boot this stack up with docker swarm:
#    docker stack deploy -c docker-compose-db.yml ships-services
#

services:

  ships-service-db:
    image: postgres:12.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=ships-db
      - POSTGRES_USER=ships-db
      - POSTGRES_PASSWORD=aak7QWDDcrM9mQnUFf9
    deploy:
      replicas: 1
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 7s
      timeout: 5s
      retries: 5

#    volumes:
#      - ships-db-data:/var/lib/postgresql/data/
#
#volumes:
#  ships-db-data:
#
#
