

## example call:
# https://services.marinetraffic.com/api/exportvesseltrack/8205c862d0572op1655989d939f1496c092ksvs4/v:3/period:daily/days:3/mmsi:241486000

###
GET {{endpoint}}/{{api-key}}/v:3/period:hourly/days:10/mmsi:241486000/protocol:jsono


###
GET {{endpoint}}/{{api-key}}/v:3/period:hourly/days:2/mmsi:{{shipA}}/protocol:jsono


###
GET {{endpoint}}/{{api-key}}/v:3/period:hourly/days:2/mmsi:{{shipB}}/protocol:jsono



###  https://services.marinetraffic.com/api/exportvesseltrack/d8445923d23c722b0b6ee750c0a6302cae79fdef/v:3/period:hourly/fromdate:2021-08-10%2022:00:00/todate:2021-08-11%2022:00:00/mmsi:310627000/protocol:jsono}
GET {{endpoint}}/{{api-key}}/v:3/period:hourly/fromdate:2021-08-10%2022:00:00/todate:2021-08-11%2022:00:00/mmsi:215567000/protocol:jsono


###
GET https://services.marinetraffic.com/api/exportvesseltrack/d8445923d23c722b0b6ee750c0a6302cae79fdef/v:3/period:hourly/fromdate:2021-08-03%2022:00:00/todate:2021-08-04%2022:00:00/mmsi:9781865/protocol:jsono
