server:
  port: 8080

spring:
  application:
    name: ships
  datasource:
    username: ships-db
    password: aak7QWDDcrM9mQnUFf9
    url: jdbc:postgresql://localhost:5432/ships-db
    hikari:
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        types:
          print:
            banner: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
