name: Build Image

on:
  push:
    branches:
      - main

jobs:
  build: #see:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 15
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'

      - name: Login to GitHub Container Registry  # see: https://blog.codecentric.de/en/2021/03/github-container-registry/
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build with Gradle
        run: ./gradlew jibDockerBuild

      - name: Tag and Push the Image
        run: |
          docker image tag ships:latest ghcr.io/mwohlf/ships:latest
          docker push ghcr.io/mwohlf/ships:latest

# to deploy in AKS, see: https://roadtoalm.com/2020/09/22/using-the-github-container-registry-with-azure-kubernetes-service-aks/
